//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Fakulteti.Models.dbKonektimi
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class FakultetiEntities1 : DbContext
    {
        public FakultetiEntities1()
            : base("name=FakultetiEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<tblAfati> tblAfati { get; set; }
        public virtual DbSet<tblDepartamenti> tblDepartamenti { get; set; }
        public virtual DbSet<tblKlasa> tblKlasa { get; set; }
        public virtual DbSet<tblKomuna> tblKomuna { get; set; }
        public virtual DbSet<tblLenda> tblLenda { get; set; }
        public virtual DbSet<tblLendaKlasa> tblLendaKlasa { get; set; }
        public virtual DbSet<tblParaqitjaProvimeve> tblParaqitjaProvimeve { get; set; }
        public virtual DbSet<tblPerdoruesi> tblPerdoruesi { get; set; }
        public virtual DbSet<tblProfesori> tblProfesori { get; set; }
        public virtual DbSet<tblProfesoriLenda> tblProfesoriLenda { get; set; }
        public virtual DbSet<tblRoli> tblRoli { get; set; }
        public virtual DbSet<tblStudenti> tblStudenti { get; set; }
        public virtual DbSet<tblStudentiLenda> tblStudentiLenda { get; set; }
        public virtual DbSet<tblViti> tblViti { get; set; }
    }
}
