//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Fakulteti.Models.dbKonektimi
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblAfati
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblAfati()
        {
            this.tblParaqitjaProvimeve = new HashSet<tblParaqitjaProvimeve>();
        }
    
        public int AfatiID { get; set; }
        public string Afati { get; set; }
        public System.DateTime DataFillimit { get; set; }
        public System.DateTime DataMbarimit { get; set; }
        public bool Aktiv { get; set; }
        public Nullable<int> NumriProvimeve { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblParaqitjaProvimeve> tblParaqitjaProvimeve { get; set; }
    }
}
