//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Fakulteti.Models.dbKonektimi
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblLendaKlasa
    {
        public int LendaKlasaID { get; set; }
        public int LendaID { get; set; }
        public int KlasaID { get; set; }
        public System.DateTime Koha { get; set; }
    
        public virtual tblKlasa tblKlasa { get; set; }
        public virtual tblLenda tblLenda { get; set; }
    }
}
