//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Fakulteti.Models.dbKonektimi
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblPerdoruesi
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblPerdoruesi()
        {
            this.tblParaqitjaProvimeve = new HashSet<tblParaqitjaProvimeve>();
            this.tblProfesoriLenda = new HashSet<tblProfesoriLenda>();
            this.tblStudentiLenda = new HashSet<tblStudentiLenda>();
        }
    
        public int PerdoruesiID { get; set; }
        public int RoliID { get; set; }
        public int DepartamentiID { get; set; }
        public int KomunaID { get; set; }
        public string Emri { get; set; }
        public string Mbiemri { get; set; }
        public System.DateTime Datelindja { get; set; }
        //public System.DateTime DataRegjistrimit { get; set; }
        public string Telefoni { get; set; }
        public string Perdoruesi { get; set; }
        public string Fjalekalimi { get; set; }
        public string Salt { get; set; }
        public bool Aktiv { get; set; }
    
        public virtual tblDepartamenti tblDepartamenti { get; set; }
        public virtual tblKomuna tblKomuna { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblParaqitjaProvimeve> tblParaqitjaProvimeve { get; set; }
        public virtual tblRoli tblRoli { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblProfesoriLenda> tblProfesoriLenda { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblStudentiLenda> tblStudentiLenda { get; set; }
    }
}
