//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Fakulteti.Models.dbKonektimi
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblProfesoriLenda
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblProfesoriLenda()
        {
            this.tblParaqitjaProvimeve = new HashSet<tblParaqitjaProvimeve>();
            this.tblStudentiLenda = new HashSet<tblStudentiLenda>();
        }
    
        public int ProfesoriLendaID { get; set; }
        public int ProfesoriID { get; set; }
        public int LendaID { get; set; }
    
        public virtual tblLenda tblLenda { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblParaqitjaProvimeve> tblParaqitjaProvimeve { get; set; }
        public virtual tblPerdoruesi tblPerdoruesi { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblStudentiLenda> tblStudentiLenda { get; set; }
    }
}
