//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Fakulteti.Models.dbKonektimi
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblParaqitjaProvimeve
    {
        public int ParaqitjaProvimeveID { get; set; }
        public int PerdoruesiID { get; set; }
        public int ProfesoriLendaID { get; set; }
        public int AfatiID { get; set; }
        public int VitiID { get; set; }
        public Nullable<int> Nota { get; set; }
    
        public virtual tblAfati tblAfati { get; set; }
        public virtual tblPerdoruesi tblPerdoruesi { get; set; }
        public virtual tblProfesoriLenda tblProfesoriLenda { get; set; }
        public virtual tblViti tblViti { get; set; }
    }
}
