//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Fakulteti.Models.dbKonektimi
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblStudentiLenda
    {
        public int StudentiLendaID { get; set; }
        public int StudentiID { get; set; }
        public int ProfesoriLendaID { get; set; }
    
        public virtual tblPerdoruesi tblPerdoruesi { get; set; }
        public virtual tblProfesoriLenda tblProfesoriLenda { get; set; }
    }
}
