//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Fakulteti.Models.dbKonektimi
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblStudenti
    {
        public int StudentiID { get; set; }
        public string Emri { get; set; }
        public string Mbiemri { get; set; }
        public System.DateTime Datelindja { get; set; }
        public int VitiStudimeve { get; set; }
        public int KomunaID { get; set; }
    }
}
